export {
  AlertIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  CartIcon,
  CheckIcon,
  CloseIcon,
  DiscountTagIcon,
  Grid2x2Icon,
  HeartIcon,
  HomeIcon,
  ImageIcon,
  InfoIcon,
  MapPinIcon,
  MenuIcon,
  MinusIcon,
  PhoneIcon,
  PlusIcon,
  SearchIcon,
  SpinnerIcon,
  TruckIcon,
  UserIcon,
  WrenchIcon,
} from './BeltIcons';
export { Grid2x2Icon as CatalogIcon } from './BeltIcons';
export type { BeltIconProps, BeltIconSize } from './BeltIcons';
